### ISSUE TITLE
Custom Sidebar with Vue?

### ISSUE THREAD

**Issue by coccoinomane** [clomie/gas-vue-typescript#27]
Hello, and thank you for this template!
May I ask whether the template can be used to make a Custom HTML sidebar in a document-bound Google Scripts?
This is the description of the sidebar from the Google documentation  > https://developers.google.com/apps-script/guides/dialogs#custom_sidebars
Thank you,
Guido

**Comment by clomie** [comment]
@coccoinomane
I didn't tried but I think it can be.
You can write `onOpen` and `showSidebar` functions as like the document you linked, instead of `doGet` function for webapps Google Scripts.

**Comment by coccoinomane** [comment]
Thank you clomie, I will try in the following weeks!
Have a nice day,
Guido
